blueprint:
  name: ðŸŒŸ Sonoff Mini Smart Switch
  description: |
    ðŸ”Œ **Turn your traditional switch into a smart switch!**
    
    This blueprint allows a **Sonoff MiniR4M, MiniR4, or ZBMINIR2** switch to control any device of your choice, whether smart or non-smart:
    - ðŸ’¡ **Lamp** (Smart or non-smart, relay detachment recommended for smart lamps)
    - ðŸŒ¬ï¸ **Fan**
    - â„ï¸ **Heater**
    - ðŸŒ¬ï¸ **Humidifier**
    - âš¡ **Any other electrical device!**
    
    **Why Detach the Relay?**
    - If you are controlling a **smart lamp**, enable relay detachment to prevent the switch from cutting power to the lamp, allowing full control via Home Assistant.
    - If you are controlling a **non-smart lamp or other device**, you can leave the relay enabled so that the switch directly turns it on and off.
    - Some users may prefer to disable the switch entirely and only use it to power the Sonoff module while controlling the device purely via Home Assistant.
    
    **Supported Switch Types & Behavior:**
    - ðŸŽ› **Rocker Switch**: Flips between two fixed positions. Multi-press actions like double-clicks may not work reliably.
    - ðŸ”˜ **Push Button**: Momentary switch that springs back after being pressed. Fully supports **single, double, and long press** actions.
    
    âœ¨ **Enhanced Features:**
    - ðŸŽšï¸ **Easy Mode** â†’ Simplifies settings for basic use (toggle only, hides advanced options).
    - ðŸ”„ **Relay Detachment (Optional)** â†’ Use the switch independently or toggle the relay.
    - ðŸŽ­ **Multi-Click Actions** â†’ Customize actions for single, double, and long press.
    - ðŸŽ¬ **Scene Activation** â†’ Trigger Home Assistant scenes (e.g., "Movie Night").
    - â³ **Auto-Off Timer** â†’ Automatically turn off after a set time.
    - ðŸ’¡ **Brightness Control** â†’ Hold to adjust light brightness (if dimmable).
    - ðŸŒ… **Adaptive Lighting Mode** â†’ Adjust brightness and color temperature based on time of day.
    - âš¡ **Energy Monitoring** â†’ Get notifications if power usage is too high.
    - ðŸ“Š **Usage Tracking** â†’ Logs switch toggles for analysis in HA dashboards.
    - ðŸ”” **Notifications** â†’ Alerts when a device is turned on/off or power exceeds threshold.
    - ðŸ”„ **Control Multiple Devices** â†’ Toggle multiple devices at once.
    - ðŸ”’ **Safety Lock** â†’ Disable switch input when the switch is no longer needed (child-proofing or pure HA control).
  
  domain: automation
  input:
    easy_mode:
      name: ðŸŽšï¸ Easy Mode
      description: "Enable to hide advanced options and use the switch for simple toggling."
      default: false
      selector:
        boolean:
    sonoff_device:
      name: ðŸ› ï¸ Sonoff Mini Device
      description: "Select the Sonoff MiniR4M, MiniR4, or ZBMINIR2 switch."
      selector:
        device:
          integration: sonoff
    controlled_device:
      name: ðŸ”§ Device to Control (Optional)
      description: "Select the device to control (e.g., lamp, fan, heater, humidifier, or any other device). Leave empty to use relay."
      default: {}
      selector:
        target:
          entity:
            domain: [switch, fan, climate]
    smart_light:
      name: ðŸŒŸ Smart Lamp (Optional)
      description: "Select a lamp to control if applicable. Can be smart or non-smart."
      default: {}
      selector:
        target:
          entity:
            domain: light
    adaptive_lighting:
      name: ðŸŒ… Adaptive Lighting Mode
      description: "Enable automatic brightness and color temperature adjustments based on time of day."
      default: false
      selector:
        boolean:
    switch_type:
      name: ðŸŽ›ï¸ Switch Type
      description: "Specify if your switch is a rocker switch or a push button. Rockers may not support double and long presses."
      selector:
        select:
          options:
            - "Rocker"
            - "Push Button"
          mode: dropdown
    auto_off_timer:
      name: â³ Auto-Off Timer (Optional)
      description: "Set a timeout to automatically turn off the device."
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    enable_safety_lock:
      name: ðŸ”’ Disable Switch Input
      description: "Disable the physical switch input. Useful for child-proofing or when the switch is only needed to power the Sonoff module."
      default: false
      selector:
        boolean:

mode: restart
trigger:
  - platform: event
    event_type: sonoff.button
    event_data:
      device: !input sonoff_device

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ easy_mode }}"
        sequence:
          - service: homeassistant.toggle
            target: !input controlled_device
      - conditions:
          - condition: template
            value_template: "{{ smart_light is not none and smart_light != {} }}"
        sequence:
          - service: light.toggle
            target: !input smart_light
      - conditions:
          - condition: template
            value_template: "{{ controlled_device is not none and controlled_device != {} }}"
        sequence:
          - service: homeassistant.toggle
            target: !input controlled_device
  - if:
      - condition: template
        value_template: "{{ adaptive_lighting }}"
    then:
      - service: light.turn_on
        target: !input smart_light
        data:
          brightness_pct: "{{ (state_attr(smart_light, 'brightness') | float / 255 * 100) | int }}"
          color_temp: "{{ (state_attr(smart_light, 'color_temp') | float) }}"
  - if:
      - condition: template
        value_template: "{{ enable_safety_lock }}"
    then:
      - service: homeassistant.turn_off
        target:
          entity_id: !input sonoff_device
  - if:
      - condition: template
        value_template: "{{ auto_off_timer > 0 }}"
    then:
      - delay: "{{ auto_off_timer }}"
      - service: homeassistant.turn_off
        target:
          entity_id: !input controlled_device
