blueprint:
  name: "Sonoff Mini Smart Switch"
  description: |
    🔌 **Advanced Sonoff Smart Switch Automation!**
    
    This blueprint provides flexible control over **Sonoff MiniR4M, MiniR4, ZBMINIR2, and other compatible devices**. It supports various switch behaviors, relay detachment, and smart automation for fans, lights, and other appliances.
    
    **Supported Home Assistant Integrations:**
    - 🏠 **ZHA (Zigbee Home Automation)** → For Zigbee-based Sonoff devices like the ZBMINIR2.
    - 🌐 **SonoffLAN** → For WiFi-based Sonoff devices, ensuring local control.
    
    **Important Setup Instructions for eWeLink Users:**
    - If using **SonoffLAN**, enable **LAN mode** in the **eWeLink app**.
    - For devices supporting **relay detachment**, enable the setting in eWeLink under **Device Settings → Detach Relay**.
    - Ensure the device is correctly added to Home Assistant under **SonoffLAN or ZHA**.
    
    **How It Works:**
    - The Sonoff device detects state changes from an attached dumb switch through its **S1/S2 terminals**.
    - If using **SonoffLAN**, button presses are tracked via **state changes in the `switch` entity**.
    - If using **ZHA**, button presses are tracked via **state changes in a `binary_sensor` entity**.
    - If the device is in **relay mode**, pressing the dumb switch will toggle the relay.
    - If in **detached mode**, the switch state is sent to Home Assistant without toggling the relay.
    - Home Assistant then determines the appropriate action based on your selected mode.
    
    **Supported Sonoff Devices & Setup:**
    - 🟢 **Sonoff MiniR4M** → Relay detachment enabled by default.
    - 🔵 **Sonoff MiniR4** → Relay detachment must be manually enabled in eWeLink.
    - 🟠 **Sonoff ZBMINIR2** → Zigbee-based with local control via ZHA.
    - ⚙️ **Other Sonoff Models** → Default settings applied.
    
    **Control Options:**
    - 💡 **Smart or Dumb Lamp** (Toggle power or use detached mode)
    - 🌬 **Bathroom Fan** (Humidity-based and manual control)
    - ⚙️ **Any Smart or Non-Smart Device** (Multiple device control)
    
    **Bathroom Fan Automation:**
    - 🖲 **Manual Mode** → Turns on when switch is pressed for a preset duration.
    - 🌫 **Auto Mode** → Activates when humidity exceeds a set threshold.
    - 🚿 **Shower Detection** → Detects rapid humidity increase.
    - 🔄 **Hybrid Mode** → Both manual and automatic activation.
    - ⏳ **Adaptive Runtime** → Runs based on humidity duration.
    - 🔘 **Manual Override** → Allows manual activation of the fan for a user-defined preset duration.
    
    **Switch Configurations:**
    - 🎚 **Rocker Switch** → Classic toggle behavior.
    - 🔘 **Push Button** → Supports single, double, and long press actions.
      - **Single Press** → Toggles the assigned device.
      - **Double Press** → Activates a scene (if selected).
      - **Long Press (Based on Selected Control Type)**:
        - **Lamp:** Dims the light or toggles a secondary scene.
        - **Fan:** Turns on the fan for a user-defined duration.
        - **Other:** Toggles an additional device or a predefined action.
    
    **Control Modes Explained:**
    - 🔄 **Relay Toggle** → Directly toggles the power of the selected device (e.g., light, fan).
    - 🔌 **Detached Mode** → The switch acts as an input only and does not toggle the relay; this is useful for smart automations.
    - 🎬 **Smart Scene** → The switch is used to activate a predefined Home Assistant scene, allowing multiple devices to be controlled simultaneously.
    
    **Additional Features:**
    - 🔄 **Relay Detachment (Optional)**
    - 🎬 **Scene Activation Support**
    - 🔄 **Multiple Device Control**
    - 🕒 **Time-Based Scheduling**
    - 📊 **Adaptive Fan Runtime Based on Humidity**
    - ⏱ **Frequent Humidity Polling (Every 30 Seconds)**
    - 🔍 **Improved Sonoff Switch Filtering**
    - 🔎 **Dynamic Filtering for Devices to Control**
    - ⏳ **Manual Fan Activation with Custom Runtime**

  domain: automation
  input:
    sonoff_switch:
      name: "Sonoff Switch"
      description: "Select the Sonoff switch entity."
      selector:
        entity:
          domain: 
            - switch
            - binary_sensor
          integration: sonoff

    device_to_control:
      name: "Device to Control"
      description: "Select the device(s) that will be controlled."
      selector:
        entity:
          domain: 
            - light
            - fan
            - switch
          multiple: true

    fan_humidity_sensor:
      name: "Humidity Sensor (Optional)"
      description: "Select a humidity sensor for automated fan control."
      default: ''
      selector:
        entity:
          domain: sensor
          device_class: humidity
          multiple: false

    humidity_threshold:
      name: "Humidity Threshold (%)"
      description: "Trigger fan activation when humidity exceeds this value."
      default: 70
      selector:
        number:
          min: 50
          max: 90
          unit_of_measurement: "%"

    fan_runtime:
      name: "Fan Runtime (minutes)"
      description: "How long the fan runs after activation."
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutes"

trigger:
  - platform: state
    entity_id: !input fan_humidity_sensor
    above: !input humidity_threshold
  - platform: state
    entity_id: !input sonoff_switch
    to: "on"
  - platform: event
    event_type: sonoff.button
    event_data:
      entity_id: !input sonoff_switch
      click_type: single
  - platform: event
    event_type: sonoff.button
    event_data:
      entity_id: !input sonoff_switch
      click_type: double
  - platform: event
    event_type: sonoff.button
    event_data:
      entity_id: !input sonoff_switch
      click_type: long
  - platform: time_pattern
    seconds: "/30"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ control_type == 'Fan' }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input device_to_control
          - delay:
              minutes: !input fan_runtime
          - service: switch.turn_off
            target:
              entity_id: !input device_to_control
      - conditions:
          - condition: template
            value_template: "{{ control_type == 'Lamp' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input device_to_control
