blueprint:
  name: ⚡ Sonoff Universal Smart Switch
  description: |
    🔌 **Customize Your Sonoff Smart Switch Setup!**
    
    This blueprint lets you use **Sonoff MiniR4M, MiniR4, ZBMINIR2, and other Sonoff devices** to control different types of devices and configure their behavior.
    
    🏠 **Device Selection:** Choose your Sonoff model and what device you want to control, and the blueprint will adapt accordingly.
    
    **Supported Sonoff Devices & Setup Requirements:**
    - 🟢 **Sonoff MiniR4M** → Relay detachment enabled by default.
    - 🔵 **Sonoff MiniR4** → Supports relay detachment (enable manually in eWeLink).
    - 🟠 **Sonoff ZBMINIR2** → Zigbee model with local control.
    - 🔴 **Sonoff TX Series** → Wall touch switch with multiple buttons.
    - ⚪ **Sonoff BasicR3** → Simple Wi-Fi relay switch.
    - ⚫ **Sonoff S26** → Smart plug with remote control.
    - ⚙️ **Other Sonoff Models** → Default settings applied.
    
    **What Can You Control?**
    - 💡 **Smart Lamp** (Relay detachment recommended)
    - 💡 **Dumb Lamp** (Relay toggles power)
    - 🌬 **Bathroom Fan** (Manual & humidity-based automation)
    - 🔥 **Heater**
    - 💨 **Humidifier**
    - ⚙️ **Any Smart or Non-Smart Device**
    
    **Bathroom Fan Features:**
    - 🖲 **Manual Mode** → Press the switch to run the fan for a set time.
    - 🌫 **Automatic Mode** → The fan turns on when humidity exceeds a threshold.
    - 🚿 **Shower Detection** → Detects rapid humidity increases and starts the fan.
    - 🔄 **Hybrid Mode** → The fan runs manually when pressed and also activates via humidity detection.
    - ⏳ **Custom Fan Runtime** → Set how long the fan runs after activation.
    - 📉 **Auto Off by Humidity** → Optionally turn off the fan when humidity drops.
    
    **Switch Type Behavior:**
    - 🎚 **Rocker Switch** → Stays in either "on" or "off" position. Best for simple toggling.
    - 🔘 **Push Button** → A momentary switch that supports **single, double, and long press** actions.
    
    **Additional Features:**
    - 🔄 **Relay Detachment (Optional)** → Use the switch independently or toggle the relay.
    - 🎭 **Multi-Click Actions** → Customize single, double, and long press actions.
    - 🎬 **Scene Activation** → Trigger Home Assistant scenes.
    - 🌞 **Adaptive Lighting** → Adjust brightness & color temperature by time of day.
    - ⚡ **Energy Monitoring** → Get notifications if power usage is too high.
    - 📊 **Usage Tracking** → Log switch toggles for analysis.
    - 🔔 **Notifications** → Alerts when a device turns on/off.
    - 🔄 **Control Multiple Devices** → Toggle multiple devices at once.
    - 🔒 **Safety Lock** → Disable switch input when needed.
    - 🟢 **Easy Mode & Advanced Mode** → Quick setup for beginners or full customization for advanced users.
    
  domain: automation
  input:
    easy_mode:
      name: 🟢 Easy Mode
      description: "Enable Easy Mode for a simplified setup or Advanced Mode for full customization."
      default: true
      selector:
        boolean:
    device_type:
      name: 📌 What Do You Want to Control?
      description: "Choose the type of device you want to control."
      selector:
        select:
          options:
            - "Smart Lamp"
            - "Dumb Lamp"
            - "Bathroom Fan"
            - "Heater"
            - "Humidifier"
            - "Other Device"
          mode: dropdown
    sonoff_model:
      name: 🏷 Sonoff Model
      description: "Select your Sonoff device. This will adjust settings automatically."
      selector:
        select:
          options:
            - "Sonoff MiniR4M"
            - "Sonoff MiniR4"
            - "Sonoff ZBMINIR2"
            - "Sonoff BasicR3"
            - "Sonoff TX Series"
            - "Sonoff S26"
            - "Other"
          mode: dropdown
      default: "Sonoff MiniR4M"
    switch_type:
      name: 🎚 Switch Type
      description: "Select your switch type."
      selector:
        select:
          options:
            - "Rocker"
            - "Push Button"
          mode: dropdown
    controlled_device:
      name: 🎛 Device to Control
      description: "Select the device you want to control."
      default: {}
      selector:
        target:
          entity:
            domain: [switch, fan, climate, light]
    enable_relay_detach:
      name: 🔄 Detach Relay
      description: "Detach relay for smart lamps so the switch acts as a trigger without cutting power."
      default: false
      selector:
        boolean:
    enable_adaptive_lighting:
      name: 🌞 Adaptive Lighting Mode
      description: "Enable automatic brightness and color temperature adjustments."
      default: false
      selector:
        boolean:
    enable_energy_monitoring:
      name: ⚡ Energy Monitoring
      description: "Enable notifications if power usage is too high."
      default: false
      selector:
        boolean:
    enable_usage_tracking:
      name: 📊 Usage Tracking
      description: "Enable logging of switch toggles for analytics."
      default: false
      selector:
        boolean:
    enable_safety_lock:
      name: 🔒 Disable Switch Input
      description: "Disable the physical switch input if you don’t need manual control."
      default: false
      selector:
        boolean:
    auto_off_timer:
      name: ⏳ Auto-Off Timer (Optional)
      description: "Set a timeout to automatically turn off the controlled device."
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    humidity_sensor:
      name: 🌫 Humidity Sensor (For Bathroom Fan)
      description: "Select a humidity sensor to automate the fan."
      default: {}
      selector:
        entity:
          domain: sensor
    humidity_threshold:
      name: 📈 Humidity Threshold
      description: "Set the humidity level to activate the fan."
      default: 70
      selector:
        number:
          min: 40
          max: 100
          unit_of_measurement: "%"
    humidity_off_threshold:
      name: 📉 Auto Off Humidity Threshold
      description: "Set the humidity level at which the fan should turn off."
      default: 50
      selector:
        number:
          min: 30
          max: 70
          unit_of_measurement: "%"
    fan_runtime:
      name: ⏳ Fan Runtime
      description: "Set how long the fan should run after activation."
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    shower_detection:
      name: 🚿 Shower Detection
      description: "Enable automatic fan activation when a rapid humidity increase is detected."
      default: false
      selector:
        boolean:
  
mode: restart
max_exceeded: silent
